"""Add available_predict_count column for User table

Revision ID: de8bb94a1dff
Revises: 
Create Date: 2024-04-04 15:55:18.489570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import os
from dotenv import load_dotenv

load_dotenv()

# revision identifiers, used by Alembic.
revision: str = 'de8bb94a1dff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('available_predict_count', sa.Integer(), nullable=True, server_default=os.getenv("MAX_PREDICT_NUMBER_AFTER_PAID")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_predict_count')
    # ### end Alembic commands ###
